services:
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: toor
      POSTGRES_DB: komento-api-db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [ "start-dev"]
    ports:
      - 9090:8080
